function ConvertTo-JiraTable
{
    param
    (
        [Parameter(Mandatory, Position = 0)]
        [string[]]$Output
    )

    if ($Output.Count -eq 1)
    {
        $Output = $Output -split '\r?\n'
    }

    $Global:Output = $Output |
        where {-not [string]::IsNullOrWhiteSpace($_)} |
        where {$_ -notmatch 'WHAM Output generated by'} |
        where {$_ -notmatch '-----------------------'} |
        where {$_ -notmatch 'table\]'} |
        foreach {$_ -replace '\[tr\]\[td\]\[b\]', '|| ' -replace '\[/b\]\[/td\]\[td\]\[b\]', ' || ' -replace '\[/b\]\[/td\]\[/tr\]', ' ||'} |
        foreach {$_ -replace '\[tr\]\[td\]', '| ' -replace '\[/td\]\[td\]', ' | ' -replace '\[/td\]\[/tr\]', ' |'} |
        foreach {$_ -replace '(?<=\|\s*)-'}

    $Output | Out-String
}
ConvertTo-JiraTable $OUtput